FROM python:3.10

WORKDIR /app
COPY . /app

RUN pip install kafka-python pymongo

CMD ["python", "consumer.py"]
FROM python:3.10

WORKDIR /app
COPY . /app

RUN pip install kafka-python pymongo

CMD ["python", "Consumer.py"]
